### ISSUE TITLE
OnyxBackupVM appends VMs specified with -e option instead of replacing

### ISSUE THREAD

**Issue by marekzwi** [OnyxfireInc/OnyxBackupVM#21] opened 2020-07-20 11:42 UTC
Hello,
I tried to backup a single machine with the -e 'machine name' option but it doesn't work. Backup of all machines mentioned in vm_exports is performed. There are no errors in the logs. I have xcp-ng version 8.1. I tried --vm-export but that didn't change anything. What may be the problem?
Marek

**Comment by lancefogle** [comment] 2020-07-20 17:55
I have downloaded the master branch code to a host running the latest patch level of XCP-ng 8.1 and it is working exactly as it should. Can you post the exact command you are running? Also, include the --preview option to command to output the resulting config and post the output as well.

**Comment by marekzwi** [comment] 2020-07-20 18:01
./onyxbackup-vm.py -e 'dns' --preview
OnyxBackupVM running on xcp2
Started: 2020-07-20 19:58:24.717616
-----------------------------------------------------
(!) --> Skipping blank entry for excludes
(!) --> Skipping blank entry for vdi_exports

Running with these settings:
  backup_dir        = /root/backup/VMS
  space_threshold   = 20
  share_type        = nfs
  compress          = False
  max_backups       = 1
  vdi_export_format = raw
  pool_backup       = True
  host_backup       = False
  excludes (count) = 0
  excludes: 
  vdi-exports (count) = 0
  vdi-exports: 
  vm-exports (count) = 2
  vm-exports: cas, dns

As you can see I want to export only one machine and the script wants to do the two that are listed in vm-exports

**Comment by lancefogle** [comment] 2020-07-20 18:08
Do you have any customization to the config file at any of the three read locations? If so can you post your onyxbackup.cfg file(s) (sanitizing any sensitive information of course)?

**Comment by lancefogle** [comment] 2020-07-20 18:20
Also please post the full output of the same preview command but with ``-l debug``` on the end so I can see the flow of the list handling

**Comment by blu-IT** [comment] 2020-07-20 18:43
@marekzwi Is the name of the vm **exact identical** with the host vm on xcp?

I also had problems with `./onyxbackup-vm.py -e 'myvm'` and the script exported all hosts configured, but than I discoverd typos in the config an my input.

**Comment by marekzwi** [comment] 2020-07-21 06:01
[onyxbackup.cfg.gz](https://github.com/OnyxfireInc/OnyxBackupVM/files/4951547/onyxbackup.cfg.gz)

I have only one config file.

./onyxbackup-vm.py -e 'dns' --preview -l debug
(i) Determining logging configuration
(i) -> Logging config file doesn't exist: loading default configuration
(i) Setting defaults for configuration
(i) Reading updates to config from configuration files
(i) Sanitizing configuration options
(i) Validating configuration options
(i) -> Checking if space_threshold within range
(i) -> Checking if max_backups within range
(i) -> Checking if vdi_export_format is valid value
(i) -> Checking if backup_dir exists
(i) -> Checking if backup_dir writeable
(i) ---> Running command: /bin/touch "/root/backup/VMS/write.test"
(i) ---> Running command: /bin/rm -f "/root/backup/VMS/write.test"
(i) -> Checking if both vm_exports and vdi_exports are empty
-----------------------------------------------------
OnyxBackupVM running on xcp2
Started: 2020-07-21 07:32:44.913155
-----------------------------------------------------
(i) Processing VM lists
(i) ---> Running command: /opt/xensource/bin/xe vm-list is-control-domain=false is-a-snapshot=false params=name-label --minimal
(i) ---> Command output: cas,dns
(i) -> VMs in pool: ['cas', 'dns']
(i) -> Sanitized VM list: ['cas', 'dns']
(i) -> Validating excludes list
(i) --> excludes = ['']
(i) --> Checking for matches: 
(!) --> Skipping blank entry for excludes
(i) -> Validating vdi_exports list
(i) --> vdi_exports = ['']
(i) --> Checking for matches: 
(!) --> Skipping blank entry for vdi_exports
(i) -> Validating vm_exports list
(i) --> vm_exports = ['dns', 'cas', 'dns']
(i) --> Checking for matches: dns
(i) --> Match found: dns
(i) --> Checking for matches: cas
(i) --> Match found: cas
(i) --> Checking for matches: dns
(i) --> Match found: dns
(i) ---> VM ignored as it has already been matched: dns

Running with these settings:
  backup_dir        = /root/backup/VMS
  space_threshold   = 20
  share_type        = nfs
  compress          = False
  max_backups       = 2
  vdi_export_format = raw
  pool_backup       = True
  host_backup       = False
  excludes (count) = 0
  excludes: 
  vdi-exports (count) = 0
  vdi-exports: 
  vm-exports (count) = 2
  vm-exports: cas, dns

It looks like -e option added vm to the list vm-exports from onyxbackup.cfg file.

@blu-IT The name of the vm is identical with the host vm on xcp.
xe vm-list name-label=dns
uuid ( RO)           : ************************************
     name-label ( RW): dns
    power-state ( RO): running

xe vm-list name-label=cas
uuid ( RO)           : ************************************
     name-label ( RW): cas
    power-state ( RO): running

**Comment by lancefogle** [comment] 2020-07-21 15:04
@marekzwi I have confirmed this behavior. This is not intended and not sure when this bug was introduced but I will work on resolving.

As a side note, you can just remove the blank ```excludes``` and ```vdi_exports``` entries in your config file as they are always defaulted to empty unless you provide them. You providing them but leaving them blank is why you get those warnings during the run that tell you ```(!) --> Skipping blank entry for <list name>``` in both those lists.

**Comment by lancefogle** [comment] 2020-07-21 15:22
@marekzwi I edited the above comment after some review of the code

**Comment by lancefogle** [comment] 2020-07-21 16:30
@marekzwi I have added three new options to the program that allow you to, on a per-list basis, override what is in the config as opposed to appending new values. I updated the help text in the program accessible via ```./onyxbackup-vm.py --help``` as well as the README for this project to reflect the changes made. I also added clarification to the existing options that they append to the existing list unless the other flags are specified.

Please review the added options in the README for guidance on use but for your current example your command would need to read: ```./onyxbackup-vm.py -o -e 'dns'```

An official new release will be posted before long so long as no other side effects show up in testing.

**Closed** 2020-07-21 18:13 UTC
Labels: enhancement

**Comment by marekzwi** [comment] 2020-07-22 08:49
Thank you very much for a quick reaction. I just checked and everything looks fine. Good job. 
I removed blank excludes and vdi_exports. This was only entered for testing. 
Greetings from Poland
Marek
