### ISSUE TITLE
Backup script is hanging

### ISSUE THREAD

**Issue by midasi** [OnyxfireInc/OnyxBackupVM#17] opened 2020-04-06 13:00 UTC
We have the issue that the backup is sometimes hanging on "Destroying snapshot" and does not seem to progress even after waiting a long time

Example output:
--- PROD.XXX started at 14:21:18 ---
> Checking backup space
> Querying VM by name
> Verifying backup directory
> Getting VM metadata
> Checking OS type
> Backing up VM metadata
> Checking for snapshot from previous backup
-> Destroying snapshot

Last lines in debug.log
04/06/2020 02:21:18 PM - INFO: > Backing up VM metadata [ service:_backup_meta():413 ]
04/06/2020 02:21:19 PM - INFO: > Checking for snapshot from previous backup [ service:_cleanup_snapshot():495 ]
04/06/2020 02:21:19 PM - INFO: -> Destroying snapshot [ service:_cleanup_snapshot():507 ]

We use XCP-ng 8.0.1, the size of the VM in the case above was around 4.9GB

**Comment by lancefogle** [comment] 2020-04-06 15:14
I have never seen this issue and the next line before it even actually does any command or work would show the command that it is running which is a call to the xe utility from XAPI. Being as it isn't even logging that message it hasn't even begun to do any actual work or try to do anything.

That information seems to me like your server you are running it on is actually hanging but without much more information and investigation I could not discern why.

**Comment by midasi** [comment] 2020-04-06 22:15
I tried to delete the snapshot manually with the command "xe snapshot-destroy uuid=<uuid>" with the same result. The command hangs and never returns...

I investigated a bit further and found out that this issue is caused by a snapshot which was not created properly and/or crashed during the creation.

Looking at the snapshot parameters shows the following:
> xe snapshot-param-list uuid=<uuid>
Snapshot with issues (still stuck in export operations, destroy not allowed):
 allowed-operations (SRO): export; clone; copy
 current-operations (SRO): export

Snapshot without issues (was properly exported, destroy is allowed)
 allowed-operations (SRO): destroy; export; revert; clone; copy
 current-operations (SRO):

The only way to fix the snapshot seems to be a restart of the host.

**Comment by lancefogle** [comment] 2020-04-06 22:23
That would appear to be an issue with XAPI. If you have the issue again,
you can try just a ```xe-toolstack-restart``` and see if the issue is
resolved without host reboot.

You should submit a bug report to XCP-ng team as nothing in onyxbackupvm
sets the allowed operations on the snapshot but I will double check as
well. Either way post the link to the issue you create there so I can track
as well.

Also, there is no version 8.0.1 of XCP-ng. Did you mean XCP-ng 8.1? That is
the latest version.

Very Respectfully,
Lance Fogle

**Comment by lancefogle** [comment] 2020-04-06 22:33
I will do some testing and get back to you.

**Comment by midasi** [comment] 2020-04-06 22:43
You are right, "xe-toolstack-restart" is indeed enough to reset the snapshot. After that I am able to destroy it.

**Comment by lancefogle** [comment] 2020-04-10 20:34
I have tested this on the system I have available and am not able to reproduce at this time. Please provide the following so I can be sure where the issue is. This honestly sounds like an issue with XAPI toolstack specifically hanging for some reason but I would like to be sure.

- Steps to reproduce
- Config you are running with
- How are you executing the script (i.e. cron, ssh session, ansible, etc)
- Contents of /etc/centos-release file (version information of ch/xcp-ng)
- Version of OnyxBackupVM

**Comment by lancefogle** [comment] 2020-04-28 15:29
@midasi Do you have any feedback per the information I requested above?

**Closed** 2020-05-01 13:57 UTC
Labels: feedback needed
